# Generated by Django 2.1.2 on 2018-10-28 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181028_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescatado',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo'),
            preserve_default=False,
        ),
    ]
