# Generated by Django 2.1.2 on 2018-10-28 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rescatado_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescatado',
            old_name='text',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='rescatado',
            old_name='image',
            new_name='fotografia',
        ),
        migrations.RemoveField(
            model_name='rescatado',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='rescatado',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='rescatado',
            name='title',
        ),
        migrations.AddField(
            model_name='rescatado',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rescatado',
            name='raza',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
