# Generated by Django 2.1.2 on 2018-10-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181028_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescatado',
            name='estado',
            field=models.CharField(choices=[('rescatado', 'Rescatado'), ('disponible', 'Disponible'), ('adoptado', 'Adoptado')], default='rescatado', max_length=10),
        ),
    ]
