# Generated by Django 2.1.2 on 2018-10-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181029_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('run', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
