# Generated by Django 2.1.2 on 2018-10-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_formulario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
